trigger: none
pr: none

variables:
- template: environment/dev.yaml
  
pool:
  name: 'nbakspools' 


parameters:

stages:
- stage: Deploy_TO_Created_Namespace
  pool:
    name: $(agent-pool-name)
  jobs:
    - template: templates/build/deploytons.yml



    