trigger: none
pr: none

variables:
- template: environment/dev.yaml
  
pool:
  name: 'nbakspools' 

parameters:
- name: environment
  displayName: Environment
  type: string
  default:
    dev
  values:
    - dev
- sqlservername: ''
- sqlelasticpoolname: ''
- firms : ['nbtenant1', 'nbtenant2', 'nbtenant3'] #defining array here to expect multiple values. 
- resourcegroupname: ''

stages:
- stage: Build_Images
  pool:
    name: $(agent-pool-name)
  jobs:
    - template: templates/build/build.yml



    