trigger: none
pr: none

variables:
- template: environment/dev.yaml
  namespaceName: 'nginx-ingress'
  imageName: 'pipelinetried'
  DOCKER_BUILDKIT: 1
  
pool:
  name: 'nbakspools' 

parameters:
- name: environment
  displayName: Environment
  type: string
  default:
    dev
  values:
    - dev

stages:
- stage: Build_Images
  pool:
    name: $(agent-pool-name)
  jobs:
    - template: templates/build/build.yml

    