trigger: none
pr: none

variables:
- template: environment/dev.yaml
  
pool:
  name: 'nbakspools' 


parameters:
  - name: users
    type: object
    default:
      - name: 'john'
        email: 'john@doe.com'
      - name: 'jane'
        email: 'jane@doe.com'
      - bob

stages:
- stage: Build_Images
  pool:
    name: $(agent-pool-name)
  jobs:
    - template: templates/build/build.yml



    