trigger:
- None

pool:
  name: 'nbakspools' 

parameters:
- name: environment
  displayName: Environment
  type: string
  default:
    dev
  values:
    - dev

variables:
  namespaceName: 'nginx-ingress'
  imageName: 'pipelines-javascript-docker'
  DOCKER_BUILDKIT: 1
- template: environment/dev.yaml

stages:
- stage: secure_buildstage
  pool:
    name: 'nbakspools'
  jobs:
  - job: secure_buildjob
    steps:
    - task: AzureCLI@2
      displayName: Get Namespace Exist
      inputs:
      azureSubscription: '$(az-subscription-id)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
          namespace=$(kubectl get namespaces | grep $(namespaceName))
          if [[ ! -z "$namespace" ]]; 
          then
            echo "Namespace exist"
          else 
            echo "Namespace Does Not Exists"
          fi
    