trigger: none
pr: none

variables:
- template: environment/dev.yaml
  
pool:
  name: 'nbakspools' 

parameters:
- name: environment
  displayName: Environment
  type: string
  default:
    dev
  values:
    - dev
- name: listOfFruits
  type: object
  default:
  - fruitName: 'apple'
    colors: ['red','green']
  - fruitName: 'lemon'
    colors: ['yellow']

stages:
- stage: Build_Images
  pool:
    name: $(agent-pool-name)
  jobs:
    - template: templates/build/build.yml



    