trigger:
- None

pool:
  name: 'nbakspools' 

parameters:
- name: environment
  displayName: Environment
  type: string
  default:
    dev
  values:
    - dev

variables:
  namespaceName: 'nginx-ingress'
  imageName: 'pipelinetried'
  DOCKER_BUILDKIT: 1
- template: environment/dev.yaml

stages:
- stage: secure_buildstage
  pool:
    name: 'nbakspools'
  jobs:
  - job: secure_buildjob
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
      repository: $(imageName)
      command: build
      Dockerfile: app/Dockerfile
    