variables:
  ### DEV ENVIRONMENT RELATED VARIABLES ###
  az-subscription-id: '612497ee-3913-4876-8bbd-25ad368306aa'
  devopscon-name: 'azureconnection'
  devops-conn-spid: 'b4c4b611-edd5-4c23-b6b1-32778a6f3513'
  # dns-azure-subscription: 'GSX Dev/Test'
  # mtlo-azure-subscription: 'Vantage-SharedResources'
  # agent-pool-name: 'Hosted-Agents-Dev'
  # aks-cluster-name: 'cbmtdev-cluster'
  # aks-resource-group: 'cbmtdev-spoke_aks'
  # mtloAzureAdDevOpsGroupID: 'e6daa15e-1abd-4c5c-9bd5-1f5748b3262c'
  # gsxAzureAdDevOpsGroupID: 'afa17ed9-8ac8-452f-adba-5312d1e9edd8'
  # vdxMartelloAdmins: 'f4bb5ee2-a0af-435f-8104-e35a88c3c4ef'
  # azureAdQAGroupID: '45097483-89b3-43ef-bd6c-235e4e80d276'
  # anpmPostgreSqlServerFQDN: 'cbmtdev-vdxanpmpg01.postgres.database.azure.com'
  # anpmPostgreSqlServerName: 'cbmtdev-vdxanpmpg01'
  # appGwPublicIp: '51.136.85.225'
  # azureContainerRegistry: 'cbmtdev.azurecr.io'
  # vdxContainerRegistry: 'vdxdev.azurecr.io'
  # cert-manager-sp-name: 'certmanager_cbmtdev_sp'
  # cert-manager-sp-tenantId: '4a94541d-46d6-430a-b41d-1aa6fca2b1af'
  # cert-manager-acme-server-url: 'https://acme-v02.api.letsencrypt.org/directory'
  # cert-manager-private-key-name: 'letsencrypt-staging'
  # cert-manager-registration-email: 'devops@martellotech.com'
  # cert-manager-azure-subscription-id: 'a548cb3d-0887-4b87-8460-6bf34967538b'
  # dnsZoneName: 'dev.ongsx.com'
  # dnsZoneRG: 'cbmtdev-dns'
  # elasticPoolName: 'cbmt-dev-pool1'
  # elasticSearchAzureRegion: 'azure-westeurope'
  # elasticSearchTemplateID: 'azure-io-optimized-v3'
  # elasticObservabilityID: 'c46ab9ab3bde46ff809fc9266dddbc74'
  # shared-keyvault: 'cbmt-vault-dev'
  # sqlResourceGroup: 'cbmtdev-sql'
  # sqlServerName: 'cbmtdev1'
  # vaultsNamesKeyvault: 'vaultsNamesDev'
  # vdxAppRegistrationClientId: '5fe65b8b-605a-4f60-ae1b-715ee854f932'
  # vdxDnsZoneName: 'vdxdev.mtlo.ca'
  # vdxIngressPublicIP: '20.54.178.197'
  # keyvaultsResourceGroup: 'cbmtdev-vaults'
  # location: 'westeurope'
  # rmqCluster: 'brisk-charcoal-raccoon.rmq.cloudamqp.com'
  # agentResourceGroup: 'cbmtdev-hub'
  # ### GIZMO,IQ & RM CONTAINERS VARIABLES ###
  # gizmoInstallFolderPath: 'C:\Program Files\GSX Solutions\'
  # gizmoLicenseResource: 'ceb27a7a-8c07-4266-99c1-c758318ec181'
  # gizmoLicenseTenant: '4a94541d-46d6-430a-b41d-1aa6fca2b1af'
  # gizmoLicenseUri: 'https://api-licensingwebapp.azurewebsites.net'
  # gizmoRobotManagerInstall: 'C:\Program Files (x86)\GSX Solutions\Robot Manager\'
  # gizmoRobotManagerPort: '51000'
  # gizmoRobotManagerVersion: '4.2.0.0'
  # gizmoScanconfigPackPath: 'C:\ProgramData\GSX Solutions\Downloads\'
  # gizmoScriptDBRevFolder: 'InjectAllRevisions'
  # gizmoScriptDBRevName: 'InjectAllRevisions'
  # gizmoScriptsPath: 'C:\Scripts'
  # gizmoSQLuseWindowsCreds: 'false'
  # gizmoValidatorFolderName: 'Validation.Script'
  # gizmoValidatorParametersName: 'ValidationScript-Parameters.CBMT'
  # gizmoValidatorScriptName: 'Apply.ValidationScript'
  # gizmoWebClientId: 'bc8efea5-2a0d-4181-ad8f-f0aa5b7cb525'
  # gizmoWebTenantId: 'common'
  # rmqHostnameGizmo: 'brisk-charcoal-raccoon.rmq.cloudamqp.com'
  # podsize: 'regular'
  # rmqPort: '5671'
  # rmqSSL: 'true'
  # sqlServerFQDN: 'cbmtdev1.database.windows.net'
  # ### KEYCLOAK CONTAINER VARIABLES ###
  # kc-db-port: '5432'
  # kc-db-vendor: 'postgres'
  # kcPostgreSqlServerFQDN: 'cbmtdev-vdxkcpg01.postgres.database.azure.com'
  # kcPostgreSqlServerName: 'cbmtdev-vdxkcpg01'
  # kc-theme-name: 'Vantage DX'
  # kc-vdx-smtp-auth-enabled: 'true'
  # kc-vdx-smtp-from-addr: 'noreply@vantage-dx.com'
  # kc-vdx-smtp-hostname: 'email-smtp.us-east-1.amazonaws.com'
  # kc-vdx-smtp-port: '465'
  # kc-vdx-smtp-ssl-enabled: 'true'
  # kc-vdx-smtp-starttls-enabled: 'false'
  # ### CBMT RELATED VARIABLES ###
  # cbmt-shared-keyvault: 'cbmtVaultDev'
  # ### ACI HEARTBEAT VARIABLES ###
  # heartbeat-storage-account-name: 'heartbeatvdx'
  # heartbeat-storage-account-endpoints-share-name: 'monitorsd'
  # validation-tool-client-id: '5fe65b8b-605a-4f60-ae1b-715ee854f932'
