apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrdemo-localdocker-deployment
  labels:
    app: acrdemo-localdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrdemo-localdocker
  template:
    metadata:
      labels:
        app: acrdemo-localdocker
    spec:
      containers:
        - name: acrdemo-localdocker
          image: nbacr01.azurecr.io/nbapp1/app1nginx:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80

   