apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-cpr
  annotations:
    kubernetes.io/ingress.class: nginx  
spec:
  defaultBackend:
    service:
      name: nbapp-service
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /web1
            pathType: Prefix
            backend:
              service:
                name: webservice
                port: 
                  number: 80
          - path: /web2
            pathType: Prefix
            backend:
              service:
                name: websvr-service2
                port: 
                  number: 80 