trigger: none
pr: none

variables:
- template: environment/dev.yaml
  
pool:
  name: 'nbakspools' 

stages:
- stage: Build_Images
  pool:
    name: $(agent-pool-name)
  jobs:
    - template: templates/build/build.yml

- stage: Deploy_TO_Created_Namespace
  pool:
    name: $(agent-pool-name)
  jobs:
    - template: templates/build/deploytons.yml



    