apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nbweb
  labels:
    app: nbweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbweb
  template:  
    metadata:
      labels: 
        app: nbweb
    spec:    
      containers:
        - name: nbweb
          image: vakem/nbwebapp:v1.0
          imagePullPolicy: Always
          command: ['/bin/sh']           #<-- Add Command to run at start-up
          args: ['-c','python manage.py makemigrations; python manage.py migrate; python manage.py runserver 0.0.0.0:8000']
          ports: 
            - containerPort: 8000          
          env:
            - name: DB_HOSTNAME
              value: "20.232.176.3"            
            - name: DB_PORT
              value: "3306" 
            - name: ENGINE
              value: "jango.db.backends.myql"           
            - name: DB_NAME
              value: "nexgbits"            
            - name: DB_USERNAME
              value: "valyakem"            
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password       
