apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nbweb
  labels:
    app: nbweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbweb
  template:  
    metadata:
      labels: 
        app: nbweb
    spec:    
      containers:
        - name: nbweb
          image: vakem/nbwebapp:v1.0
          imagePullPolicy: Always
          command: ['/bin/sh']           #<-- Add Command to run at start-up
          args: ['-c','python manage.py makemigrations; python manage.py migrate; python manage.py runserver 0.0.0.0:8000']
          ports: 
            - containerPort: 8000          
          env:
            - name: DEBUG
              value: 1
            - name: SQL_ENGINE
              value: "jango.db.backends.myql"
            - name: SECRET_KEY
              value: "ksdlfkslkfkskdj sdlfjskdfkj lsfjkaskf ljks"
            - name: SQL_HOST
              value: "20.232.176.3"            
            - name: SQL_PORT
              value: "3306"           
            - name: SQL_DATABASE
              value: "nexgbits"            
            - name: SQL_ROOT_USER
              value: "root"            
            - name: SQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password       
