apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nbweb
  labels:
    app: nbweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbweb
  template:  
    metadata:
      labels: 
        app: nbweb
    spec:    
      containers:
        - name: nbweb
          image: vakem/nbwebapp:v1.0
          imagePullPolicy: Always
          command: ['/bin/sh -c python manage.py makemigrations; python manage.py migrate; python manage.py runserver 0.0.0.0:8000']           #<-- Add Command to run at start-up
          ports: 
            - containerPort: 8000

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nbweb
#   labels:
#     app: nbweb
# spec:
#   selector:
#     matchLabels:
#       app: nbweb
#   template:
#     metadata:
#       labels:
#         app: nbweb
#     spec:
#       containers:
#         - image: vakem/nbwebapp:v1.0
#           name: nbweb
#           envFrom:
#           - secretRef:
#               name: nbapp-secret
#           - configMapRef:
#               name: nbappconfig
#           ports:
#             - containerPort: 8000
#               name: python 