apiVersion: v1
kind: Namespace
metadata:
  name: nbworks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: nbworks
spec:
  selector:
    matchLabels:
      app: nbworks
  template:
    metadata:
      labels:
        app: nbworks
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.48-alpine3.14
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: nbworks
spec:
  selector:
    app: nbworks
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-server-ingress
  namespace: nbworks
spec:
  ingressClassName: nginx
  rules:
  - host: nexgbitsapp.nexgbits.com
    http:
      paths:
      - path: /nbworks
        pathType: Prefix
        backend:
          service:
            name: web-server-service
            port:
              number: 5001